version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: ./novel-editor-demo/apps/web
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_PDF_SERVICE_URL=http://pdf-service:8000
    depends_on:
      - pdf-service
    networks:
      - sow-network

  # Python PDF Service
  pdf-service:
    build:
      context: ./pdf-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    networks:
      - sow-network

networks:
  sow-network:
    driver: bridge

volumes:
  node_modules: