version: '3.8'

services:
  # Next.js Frontend
  frontend:
    build:
      context: ./novel-editor-demo
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
      - "3334:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_PDF_SERVICE_URL=http://pdf-service:8000
            - OPENROUTER_API_KEY=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
      - DB_HOST=168.231.115.219
      - DB_PORT=3306
      - DB_USER=sg_sow_user
      - DB_PASSWORD=SG_sow_2025_SecurePass!
      - DB_NAME=socialgarden_sow
      - NEXT_PUBLIC_BASE_URL=http://168.231.115.219:3333
    depends_on:
      - pdf-service
    networks:
      - sow-network

  # Python PDF Service
  pdf-service:
    build:
      context: ./pdf-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    networks:
      - sow-network

networks:
  sow-network:
    driver: bridge

volumes:
  node_modules: