// Authoritative Social Garden rate card (AUD/hr)
// Source: Official spreadsheet provided by Social Garden (Oct 2025)
export type RoleRate = { name: string; rate: number };

export const ROLES: RoleRate[] = [
  { name: 'Account Management - Head Of', rate: 365.00 },
  { name: 'Account Management - Director', rate: 295.00 },
  { name: 'Account Management - Account Manager', rate: 180.00 },
  { name: 'Account Management - Account Coordinator', rate: 120.00 },
  { name: 'Account Management - Senior Account Manager', rate: 210.00 },
  { name: 'Project Management - Head Of', rate: 295.00 },
  { name: 'Project Management - Senior Project Manager', rate: 210.00 },
  { name: 'Project Management - Project Manager', rate: 180.00 },
  { name: 'Tech - Delivery - Project Coordination', rate: 110.00 },
  { name: 'Tech - Delivery - Project Management', rate: 150.00 },
  { name: 'Tech - Head Of - Customer Success', rate: 365.00 },
  { name: 'Tech - Head Of - Program Strategy', rate: 365.00 },
  { name: 'Tech - Head Of - Senior Project Management', rate: 365.00 },
  { name: 'Tech - Head Of - Systems', rate: 365.00 },
  { name: 'Tech - Integrations', rate: 170.00 },
  { name: 'Tech - Integrations (Senior)', rate: 295.00 },
  { name: 'Tech - Keyword Research', rate: 120.00 },
  { name: 'Tech - Landing Page - (Offshore)', rate: 120.00 },
  { name: 'Tech - Landing Page - (Onshore)', rate: 210.00 },
  { name: 'Tech - Website Optimisation', rate: 120.00 },
  { name: 'Tech - Producer - Admin', rate: 120.00 },
  { name: 'Tech - Producer - Campaign Orchestration', rate: 120.00 },
  { name: 'Tech - Producer - Chat Bot Build', rate: 120.00 },
  { name: 'Tech - Producer - Copywriting', rate: 120.00 },
  { name: 'Tech - Producer - Deployment', rate: 120.00 },
  { name: 'Tech - Producer - Design', rate: 120.00 },
  { name: 'Tech - Producer - Development', rate: 120.00 },
  { name: 'Tech - Producer - Documentation', rate: 120.00 },
  { name: 'Tech - Producer - Email', rate: 120.00 },
  { name: 'Tech - Producer - Field Marketing', rate: 120.00 },
  { name: 'Tech - Producer - Integration', rate: 120.00 },
  { name: 'Tech - Producer - Landing Page', rate: 120.00 },
  { name: 'Tech - Producer - Lead Management', rate: 120.00 },
  { name: 'Tech - Producer - Reporting', rate: 120.00 },
  { name: 'Tech - Producer - Services', rate: 120.00 },
  { name: 'Tech - Producer - SMS Setup', rate: 120.00 },
  { name: 'Tech - Producer - Support & Monitoring', rate: 120.00 },
  { name: 'Tech - Producer - Testing', rate: 120.00 },
  { name: 'Tech - Producer - Training', rate: 120.00 },
  { name: 'Tech - Producer - Web Optimisation', rate: 120.00 },
  { name: 'Tech - Producer - Workflow', rate: 120.00 },
  { name: 'Tech - SEO Producer', rate: 120.00 },
  { name: 'Tech - SEO Strategy', rate: 180.00 },
  { name: 'Tech - Specialist - Admin', rate: 180.00 },
  { name: 'Tech - Specialist - Campaign Orchestration', rate: 180.00 },
  { name: 'Tech - Specialist - Complex Workflow', rate: 180.00 },
  { name: 'Tech - Specialist - Database Management', rate: 180.00 },
  { name: 'Tech - Specialist - Email', rate: 180.00 },
  { name: 'Tech - Specialist - Integration', rate: 180.00 },
  { name: 'Tech - Specialist - Integration (Snr)', rate: 190.00 },
  { name: 'Tech - Specialist - Lead Management', rate: 180.00 },
  { name: 'Tech - Specialist - Program Strategy', rate: 180.00 },
  { name: 'Tech - Specialist - Reporting', rate: 180.00 },
  { name: 'Tech - Specialist - Services', rate: 180.00 },
  { name: 'Tech - Specialist - Testing', rate: 180.00 },
  { name: 'Tech - Specialist - Training', rate: 180.00 },
  { name: 'Tech - Specialist - Workflow', rate: 180.00 },
  { name: 'Tech - Sr. Architect - App Development', rate: 365.00 },
  { name: 'Tech - Sr. Architect - Consultation', rate: 365.00 },
  { name: 'Tech - Sr. Architect - Data Migration', rate: 365.00 },
  { name: 'Tech - Sr. Architect - Integration Strategy', rate: 365.00 },
  { name: 'Tech - Sr. Consultant - Advisory & Consultation', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - Analytics', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - Audit', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - Campaign Strategy', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - CRM Strategy', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - Data Migration', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - Field Marketing', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - Services', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - Solution Design', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - Technical', rate: 295.00 },
  { name: 'Tech - Sr. Consultant - Strategy', rate: 295.00 },
  { name: 'Tech - Specialist - Research', rate: 180.00 },
  { name: 'Content - Campaign Strategy', rate: 180.00 },
  { name: 'Content - Keyword Research', rate: 120.00 },
  { name: 'Content - Keyword Research (Senior)', rate: 150.00 },
  { name: 'Content - Optimisation', rate: 150.00 },
  { name: 'Content - Reporting (Offshore)', rate: 120.00 },
  { name: 'Content - Reporting (Onshore)', rate: 150.00 },
  { name: 'Content - SEO Copywriting', rate: 150.00 },
  { name: 'Content - SEO Strategy', rate: 210.00 },
  { name: 'Content - Website Optimisation', rate: 120.00 },
  { name: 'Content - Copywriter', rate: 150.00 },
  { name: 'Copywriting (Offshore)', rate: 120.00 },
  { name: 'Copywriting (Onshore)', rate: 180.00 },
  { name: 'Design - Digital Asset (Offshore)', rate: 140.00 },
  { name: 'Design - Digital Asset (Onshore)', rate: 190.00 },
  { name: 'Design - Email (Offshore)', rate: 120.00 },
  { name: 'Design - Email (Onshore)', rate: 295.00 },
  { name: 'Design - Landing Page (Onshore)', rate: 190.00 },
  { name: 'Design - Landing page (Offshore)', rate: 120.00 },
  { name: 'Dev (or Tech) - Landing Page (Offshore)', rate: 120.00 },
  { name: 'Dev (or Tech) - Landing Page (Onshore)', rate: 210.00 },
];

export const RATE_CARD_MAP: Record<string, number> = Object.fromEntries(
  ROLES.map(r => [r.name, r.rate])
);

export const getRateForRole = (name: string): number => RATE_CARD_MAP[name] ?? 0;
